name: Boardgames CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Instaling NPM
      run: npm install
    - name: Running Unit Tests
      run: npm run test:unit
      # Add a custom step to the build script in order to display my softuni username.
    - name: Display SoftUni username
      run: echo "plamenbranyakov"
